<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Title</name>
   <tag></tag>
   <elementGuidId>a03ca42a-cfb8-48db-9e2c-20fd00f045c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/form/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.font-sans.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ea4c57a9-f462-4c8d-be46-5e00c43be1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-sans mr-2</value>
      <webElementGuid>b32d4186-ea77-4be9-83aa-87a8ffea2431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>one</value>
      <webElementGuid>2b0ff0cd-d3e8-42f9-8e6a-2e5e092bcc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>416f7d8d-ae3f-42a9-9a71-73e88aff6bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;top-0 flex justify-between items-center px-3 md:px-6 w-full h-[60px] bg-pink-200&quot;]/div[@class=&quot;w-full relative flex justify-between lg:w-auto lg:static lg:block lg:justify-start&quot;]/div[@class=&quot;flex items-center justify-center&quot;]/form[@class=&quot;flex gap-x-2&quot;]/div[1]/div[@class=&quot;flex items-center gap-x-2&quot;]/label[@class=&quot;font-sans mr-2&quot;]</value>
      <webElementGuid>be881131-6a6f-462b-ad0d-5c225b865f2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/form/div/div/label</value>
      <webElementGuid>e456dcec-5b1f-4210-a976-a54352ff103c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SearchBy:'])[1]/following::label[1]</value>
      <webElementGuid>8b7f14fa-419e-40f8-8c4c-aba0138a6e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bookmark'])[1]/following::label[1]</value>
      <webElementGuid>b3fbf713-c7da-4018-8749-f36c1c80168c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::label[1]</value>
      <webElementGuid>064252e8-0cb9-4b4e-81c5-9ec7f04a70ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/preceding::label[2]</value>
      <webElementGuid>324cd740-231d-4288-bf2a-de37bef06900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Title']/parent::*</value>
      <webElementGuid>c18fa27b-1a8d-4a2c-bdc5-a7a5f796d95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>569642d7-9cc5-4602-9bd7-a0888da349e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Title' or . = 'Title')]</value>
      <webElementGuid>fc6be001-7350-4459-b706-9f4dde5c996d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
