<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>d713839e-4d10-4bc2-a634-8cf7ff45305a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>fe6635ba-6c31-4b04-b507-6faadd3799e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z</value>
      <webElementGuid>cf7aa7b8-59fa-4b1f-85c4-e3ae07ffb719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;top-0 flex justify-between items-center px-3 md:px-6 w-full h-[60px] bg-pink-200&quot;]/div[@class=&quot;w-full relative flex justify-between lg:w-auto lg:static lg:block lg:justify-start&quot;]/div[@class=&quot;flex items-center justify-center&quot;]/form[@class=&quot;flex gap-x-2&quot;]/button[@class=&quot;flex items-center justify-center px-4 border-l&quot;]/svg[@class=&quot;w-6 h-6 text-blue-300&quot;]/path[1]</value>
      <webElementGuid>073b5494-bc7f-4e2b-a6ca-4e8530d896bc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
